services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - ..:/workspaces/nkmzbot:cached
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/workspaces/nkmzbot/target
    environment:
      # devcontainer 内でアクセスできるように上書き
      - WEB_BIND=0.0.0.0:3000
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - DISCORD_REDIRECT_URI=http://localhost:3000/oauth/callback
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  cargo-cache:
  target-cache:
  pgdata:
