services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - ..:/workspaces/nkmzbot:cached
      - go-mod-cache:/go/pkg/mod
    environment:
      # devcontainer 内でアクセスできるように上書き
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    depends_on:
      - db

  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  go-mod-cache:
  pgdata:
